name: Multiarch build
on:
  push:
  pull_request:

env:
  IMAGE_TAG: v1 ${{ github.sha }}
  IMAGE_NAME: multi-arch-test
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: mayurwaghmode111

jobs:
  build-multiplatform-containerfile:
    name: Build multi-platform image using Dcokerfile
    runs-on: ubuntu-20.04
    steps:
      - name: add checkout action...
        uses: actions/checkout@v2
        
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
            
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@main
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          archs: amd64, ppc64le
          containerfiles: |
            ./Dockerfile
      # Push the image manifest to Quay.io (Image Registry)
      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PWD }}

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
